[package]
name = "vip"
version = "0.0.1"

[addresses]
std = "0x1"
vip = "0xabf0daba43f9b92484f8f3f5f8dfcc0e5382b07304a32d4fe444fc463ffd5451"
vesting = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }
initia-vesting = { git = "https://github.com/initia-labs/vesting.git", rev = "main" }