[package]
name = "vip"
version = "0.0.1"

[addresses]
std = "0x1"
vip = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"
vesting = "0x2"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "982838607179f425593f33638fb0967c93fdacdc" }
initia-vesting = { git = "https://github.com/initia-labs/vesting.git", rev = "9f248af915a20343bc4eee8ab6c2aa598992bf11" }