[package]
name = "vip"
version = "0.0.1"

[addresses]
std = "0x1"
vip = "0x9065fda28f52bb14ade545411f02e8e07a9cb4ba"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "0a6aa67b41087c56b6fe7ae54e75c0ecceb388a8" }
