[package]
name = "vip"
version = "0.0.1"

[addresses]
std = "0x1"
vip = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "0a6aa67b41087c56b6fe7ae54e75c0ecceb388a8" }
