[package]
name = "vip"
version = "1.2.0"

[addresses]
std = "0x1"
vip = "_"
vesting = "_"

[dev-addresses]
vip = "0x2"
vesting = "0x3"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }
initia-vesting = { git = "https://github.com/initia-labs/vesting.git", rev = "main" }