[package]
name = "initia-vesting"
version = "0.0.1"

[addresses]
std = "0x1"
vesting = "0x2"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "0a6aa67b41087c56b6fe7ae54e75c0ecceb388a8" }
